import type { FC } from 'react'
import Head from 'next/head'
import Footer from '@components/footer'

const DefaultLayout: FC = ({ children }) => {
  return (
    <>
      <Head>
        <title>Next.js Black Belt 🥋</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="double-flow">
        <div>{children}</div>
        <Footer />
      </main>
    </>
  )
}

export { DefaultLayout }
